# what_were_covering
0. An end-to-end Scikit-learn workflow
1. Getting the data ready
2. choosing the right estimator/algorithm for our problems
3. fit the model/algorithm and use it to make predictions on our data
4. evelauate a model
5. improve a model
6. save and laod a trained model
7. putting it all together

In [1]:
# standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# | Getting our data ready to be used with machine learning 
three main things we have to do 
1. split the data into features and labels ( usually "x", "y")
2. filling ( also called imputing ) or disregarding missing values 
3. converting non-numerical values to numerical values ( also called feature encoding)

In [2]:
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
x = heart_disease.drop("target", axis =1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [5]:
y = heart_disease["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
clf = RandomForestClassifier()

In [8]:
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [9]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [11]:
clf.fit(x_train,y_train);

In [12]:
x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
111   57    1   2       150   126    1        1      173      0      0.2   
10    54    1   0       140   239    0        1      160      0      1.2   
82    60    0   2       102   318    0        1      160      0      0.0   
299   45    1   3       110   264    0        1      132      0      1.2   
178   43    1   0       120   177    0        0      120      1      2.5   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
124   39    0   2        94   199    0        1      179      0      0.0   
43    53    0   0       130   264    0        0      143      0      0.4   
180   55    1   0       132   353    0        1      132      1      1.2   
122   41    0   2       112   268    0        0      172      1      0.0   
71    51    1   2        94   227    0        1      154      1      0.0   

     slope  ca  thal  
111      2   1     3  
10       2   0     2  
82       2   1     2  
299      1   0     3  
178      1   0     3  
..     ...  ..   ...  
124      2   0     2  
43       1   0     2  
180      1   1     3  
122      2   0     2  
71       2   1     3  

[242 rows x 13 columns]

In [13]:
x_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
252   62    0   0       138   294    1        1      106      0      1.9   
14    58    0   3       150   283    1        0      162      0      1.0   
3     56    1   1       120   236    0        1      178      0      0.8   
255   45    1   0       142   309    0        0      147      1      0.0   
19    69    0   3       140   239    0        1      151      0      1.8   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
170   56    1   2       130   256    1        0      142      1      0.6   
130   54    0   2       160   201    0        1      163      0      0.0   
89    58    0   0       100   248    0        0      122      0      1.0   
232   55    1   0       160   289    0        0      145      1      0.8   
150   66    1   0       160   228    0        0      138      0      2.3   

     slope  ca  thal  
252      1   3     2  
14       2   0     2  
3        2   0     2  
255      1   3     3  
19       2   2     2  
..     ...  ..   ...  
170      1   1     1  
130      2   1     2  
89       1   0     2  
232      1   1     3  
150      2   0     1  

[61 rows x 13 columns]

In [14]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [15]:
x.shape

(303, 13)

In [16]:
x.shape[0] * 0.8

242.4

In [17]:
242 + 61

303

In [18]:
len(heart_disease)

303

# Cleaning Data 
1.1 Make sure its all numerical

In [19]:
car_sales = pd.read_csv("car-sales-extended-missing-data.csv")
car_sales

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [20]:
car_sales.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [21]:
car_sales["Doors"]. value_counts()

4.0    811
5.0     75
3.0     64
Name: Doors, dtype: int64

In [22]:
len(car_sales)

1000

In [23]:
car_sales.dtypes

Make              object
Colour            object
Odometer (KM)    float64
Doors            float64
Price            float64
dtype: object

In [24]:
# Split inti x,y
x = car_sales.drop("Price", axis =1)
y= car_sales["Price"]


In [25]:
# split into training and test
x_train, y_train,x_test, y_test = train_test_split(x,y, test_size=0.2)

In [26]:
x.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White        35431.0    4.0
1     BMW   Blue       192714.0    5.0
2   Honda  White        84714.0    4.0
3  Toyota  White       154365.0    4.0
4  Nissan   Blue       181577.0    3.0

# what if there were missing values?
1. fill them with some values( as known as imputation)
2. removed the sample with missing data altogether

In [27]:
# import car missing data
car_sales_missing = pd.read_csv("car-sales-extended-missing-data.csv")

In [28]:
car_sales_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [29]:
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [30]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [31]:
# create x and y
x = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [32]:
car_sales_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [33]:
car_sales_missing["Doors"].value_counts()

4.0    811
5.0     75
3.0     64
Name: Doors, dtype: int64

### option 1 fill missing data with pandas

In [34]:
# fill the "make" coloumn
car_sales_missing["Make"].fillna("missing", inplace =True)

# # fill the "Colour" coloumn
car_sales_missing["Colour"].fillna("missing", inplace =True) 

# fill the "Odometer (KM)" coloumn
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(),inplace=True)

# fill the "make" coloumn
car_sales_missing["Doors"].fillna(4, inplace =True)

In [35]:
# checking our data frame again
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [36]:
# remove rows with missing price values
car_sales_missing.dropna(inplace=True)


In [37]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [38]:
len(car_sales_missing)

950

In [39]:
x = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [40]:
# Turn the categorious into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)],
                                remainder="passthrough")
transformed_x = transformer.fit_transform(car_sales_missing)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

# Option 2: Fill missing value with Scikit-Learn

In [41]:
car_sales_missing = pd.read_csv("car-sales-extended-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [42]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [43]:
car_sales_missing.dropna(subset=["Price"], inplace=True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [44]:
# Split into x and y
x = car_sales_missing.drop("Price",axis=1)
y = car_sales_missing["Price"]

In [45]:
x.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [46]:
# Filling missing values with scikit-learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Filling categorical value with 'missing ' & numerical values with mean
cat_imputer = SimpleImputer(strategy="constant",fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

# Define coloumns
cat_features = ["Make","Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

# create an imputer (something that fills missing data)
imputer = ColumnTransformer([
        ("cat_imputer",cat_imputer,cat_features),
        ("door_imputer",door_imputer,door_features),
        ("num_imputer",num_imputer,num_features)
])

# Transform the data
filled_x = imputer.fit_transform(x)
filled_x


array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [47]:
car_sales_filled = pd.DataFrame(filled_x,
                               columns=["Make","Colour","Doors","Odometer (KM)"])
car_sales_filled.head()

Make Colour Doors Odometer (KM)
0   Honda  White     4         35431
1     BMW   Blue     5        192714
2   Honda  White     4         84714
3  Toyota  White     4        154365
4  Nissan   Blue     3        181577

In [48]:
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [49]:
# now we ve got our data as number and filled (no missing)
# lets fit a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split


x_train, x_test, y_train, y_test = train_test_split(transformed_x,y,test_size=0.2)

model = RandomForestRegressor()
model.fit(x_train, y_train)
model.score(x_test, y_test)


0.9998421058539825

In [50]:
len(car_sales_filled),len(car_sales)

(950, 1000)

## 2. Choosing the right estimator/algorithm for our problem
scikit-learn uses estimator as another term for machine

* Classification -- predicting whether a sample is one thing or another

* Regression -- predicting a number 

# 2.1 Picking a machine learning model for a regression problem

In [51]:
# Import Boston housing database
from sklearn.datasets import load_boston
boston = load_boston()
boston;


In [52]:
boston_df = pd.DataFrame(boston["data"], columns=boston["feature_names"])
boston_df["target"] = pd.Series(boston["target"])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [53]:
# How many samples?
len(boston_df)

506

In [54]:
# Let s try the Ridge Regression model
from sklearn.linear_model import Ridge

# Setup random seed
np.random.seed(42)

# Create the data
x = boston_df.drop("target", axis=1)
y = boston_df["target"]

# Split into train and test  sets
x_train , x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

# Instantiate Ridge model
model = Ridge()
model.fit(x_train,y_train)

# Check the score of the Ridge model on the test data
model.score(x_test,y_test)

0.6662221670168519

In [55]:
#How do we improve this score?
#What if Ridge was not working?
#https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [56]:
import numpy as np

# Let try the random Forest Regressor

In [57]:
# let try thr randon forest regressor
from sklearn.ensemble import RandomForestRegressor

# Setup random seed
np.random.seed(42)

# Create the data
x = boston_df.drop("target", axis=1)
y = boston_df["target"]

# split the data
x_test, x_train, y_test, y_train = train_test_split(x,y,test_size=0.2)

# instatiate random forest regressor
rf = RandomForestRegressor()
rf.fit(x_train, y_train)

# Evaluate the random forest regressor
rf.score(x_test, y_test)

0.8234340729453582

# Check the Ridge test again

In [58]:
model.score(x_test, y_test)

0.7487825119234439

# 2.2 Choosing an estimator for a classification problem
let fo the map https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [61]:
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [62]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [64]:
len(heart_disease)

303

# Consulting the map and its says to try LinearSVC

In [66]:
# import the LinearSVC estimator class
from sklearn.svm import LinearSVC

# setup random seed
np.random.seed(42)

# make the data
x = heart_disease.drop("target", axis=1)
y= heart_disease["target"]

# split the data
x_test, x_train, y_test, y_train = train_test_split(x,y, test_size=0.2)

# instantiate LinearSVC 
clf = LinearSVC()
clf.fit(x_train , y_train)

# eveluate the LinearSVC
clf.score(x_test,y_test)

C:\Users\Tonymore\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


0.5867768595041323

In [68]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

In [70]:
# import the LinearSVC estimator class
from sklearn.ensemble import RandomForestClassifier

# setup random seed
np.random.seed(42)

# make the data
x = heart_disease.drop("target", axis=1)
y= heart_disease["target"]

# split the data
x_test, x_train, y_test, y_train = train_test_split(x,y, test_size=0.2)

# instantiate Random Forest Classiifier
clf = RandomForestClassifier()
clf.fit(x_train , y_train)

# eveluate the Random Forest Classiifier
clf.score(x_test,y_test)

0.7892561983471075

# NOTE THIS POINT:
    1. if you have structure data, used ensemble methods
    2. if you have unstructure data, use deep learning or transfer learning

In [75]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

#  3. FITTING A MODEL/ ALGORITHM ON OUR DATA AND USED IT YO MAKE PREDICTIONS

3.1 Fitting the model to data

Different names for:
* "x" = features, features variables, data
* "y" = labels, targets, target vairables

In [76]:
# import the LinearSVC estimator class
from sklearn.ensemble import RandomForestClassifier

# setup random seed
np.random.seed(42)

# make the data
x = heart_disease.drop("target", axis=1)
y= heart_disease["target"]

# split the data
x_test, x_train, y_test, y_train = train_test_split(x,y, test_size=0.2)

# instantiate Random Forest Classiifier
clf = RandomForestClassifier()

# Fit the model to data (training the machine learning model)
clf.fit(x_train , y_train)

# eveluate the Random Forest Classiifier
clf.score(x_test,y_test)

0.7892561983471075

In [77]:
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [78]:
y.tail()

298    0
299    0
300    0
301    0
302    0
Name: target, dtype: int64

# 3.2 Making predictions using a machine learning model
2 ways to make predictions
    1. predict()
    2. predict_proba()

In [81]:
x_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
132   42    1   1       120   295    0        1      162      0      0.0   
202   58    1   0       150   270    0        0      111      1      0.8   
196   46    1   2       150   231    0        1      147      0      3.6   
75    55    0   1       135   250    0        0      161      0      1.4   
176   60    1   0       117   230    1        1      160      1      1.4   

     slope  ca  thal  
132      2   0     2  
202      2   0     3  
196      1   0     2  
75       1   0     2  
176      2   2     3

In [82]:
clf.predict(x_test)

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
      dtype=int64)

In [83]:
np.array

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1],
      dtype=int64)

In [84]:
# Use a trained model to make predictions
# clf.predict(np.array([1,7,8,3,4])) this does not worked

# Compare predictions to truth labels to eveluate the model

# Making prediction with pricdicts() model

In [85]:
y_preds = clf.predict(x_test)
np.mean(y_preds ==y_test)

0.7892561983471075

In [87]:
clf.score(x_test, y_test)

0.7892561983471075

In [92]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.7892561983471075

# Making predictions with predicts_proba()

In [95]:
# predict_proba() returns probabilities of a classification label
clf.predict_proba(x_test[:5])

array([[0.07, 0.93],
       [0.81, 0.19],
       [0.21, 0.79],
       [0.19, 0.81],
       [0.7 , 0.3 ]])

In [96]:
# lets s  predict() on the same data...
clf.predict(x_test[:5])

array([1, 0, 1, 1, 0], dtype=int64)

In [97]:
x_test[:5]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
132   42    1   1       120   295    0        1      162      0      0.0   
202   58    1   0       150   270    0        0      111      1      0.8   
196   46    1   2       150   231    0        1      147      0      3.6   
75    55    0   1       135   250    0        0      161      0      1.4   
176   60    1   0       117   230    1        1      160      1      1.4   

     slope  ca  thal  
132      2   0     2  
202      2   0     3  
196      1   0     2  
75       1   0     2  
176      2   2     3

In [99]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

# How to predict with our model (Regression)

In [102]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Create the data 
x = boston_df.drop("target", axis =1)
y = boston_df["target"]

# split into training and test sets
x_test, x_train, y_test, y_train = train_test_split(x,y, test_size=0.2)

# instantiate and fit model
model = RandomForestRegressor().fit(x_train, y_train)

# make prediction 
y_preds = model.predict(x_test)

In [104]:
y_preds[:10]

array([10.586, 21.732, 24.431, 14.221, 20.373, 25.263, 23.811, 25.121,
       10.964, 15.739])

In [105]:
np.array(y_test[:10])

array([12. , 19.9, 19.4, 13.4, 18.2, 24.6, 21.1, 24.7,  8.7, 27.5])

In [106]:
# compare the predictions to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

2.876400990099011

# How to Evaluating A machine Learning model (score)

Three ways to evealuate scikit-learn model/esitmators:
1. Estimator score method
2. the scoring parameter
3. Problem-specific metric functions




In [110]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

x = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# split into training and test sets
x_test, x_train, y_test, y_train = train_test_split(x,y,test_size=0.2)

# instantiate and fit model
clf = RandomForestClassifier()

# fit prediction
clf.fit(x_train, y_train)


RandomForestClassifier()

In [111]:
clf.score(x_train, y_train)

1.0

In [112]:
clf.score(x_test,y_test)

0.7892561983471075

# Let do the same for regression 

In [115]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

x = boston_df.drop("target", axis=1)
y = boston_df["target"]

# split into training and test sets
x_test, x_train, y_test, y_train = train_test_split(x,y,test_size=0.2)

# instantiate and fit model
model = RandomForestRegressor().fit(x_train, y_train)


In [116]:
model.score(x_test,y_test)

0.8234340729453582

#### Evaluating a model using the scoring parameter

In [119]:
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

x = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# split into training and test sets
x_test, x_train, y_test, y_train = train_test_split(x,y,test_size=0.2)

# instantiate and fit model
clf = RandomForestClassifier()

# fit prediction
clf.fit(x_train, y_train)

RandomForestClassifier()